<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <UserSecretsId>98b9107b-50df-4fe8-976e-68dbddd5691b</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="CarReservation.DataAccess\**" />
    <Compile Remove="CarReservation.Models\**" />
    <Compile Remove="CarReservation.Utility\**" />
    <Compile Remove="wwwroot\certs\**" />
    <Content Remove="CarReservation.DataAccess\**" />
    <Content Remove="CarReservation.Models\**" />
    <Content Remove="CarReservation.Utility\**" />
    <Content Remove="wwwroot\certs\**" />
    <EmbeddedResource Remove="CarReservation.DataAccess\**" />
    <EmbeddedResource Remove="CarReservation.Models\**" />
    <EmbeddedResource Remove="CarReservation.Utility\**" />
    <EmbeddedResource Remove="wwwroot\certs\**" />
    <None Remove="CarReservation.DataAccess\**" />
    <None Remove="CarReservation.Models\**" />
    <None Remove="CarReservation.Utility\**" />
    <None Remove="wwwroot\certs\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="Hangfire" Version="1.8.21" />
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.21" />
    <PackageReference Include="Hangfire.SqlServer" Version="1.8.21" />
    <PackageReference Include="MailKit" Version="4.13.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="8.0.18" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.MicrosoftAccount" Version="8.0.18" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.18" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Identity.Web" Version="4.3.0" />
    <PackageReference Include="Microsoft.Identity.Web.UI" Version="4.3.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />
    <PackageReference Include="Sustainsys.Saml2.AspNetCore2" Version="2.11.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="CarReservation.DataAccess\CarReservation.DataAccess.csproj" />
    <ProjectReference Include="CarReservation.Models\CarReservation.Models.csproj" />
    <ProjectReference Include="CarReservation.Utility\CarReservation.Utility.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\Identity\Data\" />
    <Folder Include="wwwroot\images\car\" />
    <Folder Include="wwwroot\images\car\" />
    <Folder Include="wwwroot\files\" />
  </ItemGroup>

  <ItemGroup>
  	<None Update="appsettings.Development.json">
  	  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  	</None>
  </ItemGroup>

</Project>
